repos:
  # black - the uncompromising Python code formatter
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        language_version: python3.8

  # flake8 - style guide enforcement
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8

  # isort - organize import correctly
  - repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
      - id: isort

  # gitlint - correct git commit format
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.15.0
    hooks:
      - id: gitlint
