apiVersion: v1
kind: Secret
metadata:
  name: {{ default .Chart.Name .Values.nameOverride }}-django-secrets
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $val := .Values.secretEnvironmentVariables }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  postgresql-host: {{ .Values.postgresql.postgresqlHost | default (printf "%s-postgresql" .Release.Name) | b64enc | quote  }}
  postgresql-user: {{ (default .Values.postgresql.auth.username .Values.global.postgresql.auth.username) | b64enc | quote }}
  postgresql-name: {{ .Values.postgresql.auth.database | b64enc | quote }}
  postgresql-password: {{ (default .Values.postgresql.auth.password .Values.global.postgresql.auth.pssword) | b64enc | quote }}
  postgresql-postgres-password: {{ (default .Values.postgresql.auth.password .Values.global.postgresql.auth.password) | b64enc | quote }}


