apiVersion: v1
kind: Service
metadata:
  name: {{ include "spacecrafts.fullname" . }}
  labels:
    {{- include "spacecrafts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.portNumber }}
      targetPort: {{ .Values.containerPort.name }}
      protocol: TCP
      name: {{ .Values.service.port.name }}
  selector:
    {{- include "spacecrafts.selectorLabels" . | nindent 4 }}